# Generated by Django 2.0.5 on 2018-10-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_register_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register_course',
        ),
    ]
